# no modificar este archivo
image: gitpod/workspace-postgres

tasks:
  - before: .gitpod/before.sh
    init: .gitpod/init.sh
    command: .gitpod/command.sh

ports:
  - port: 8000
    visibility: public
    onOpen: notify